
-- use algamoneyapi;

-- CREATE TABLE permissao(
-- 	codigo BIGINT AUTO_INCREMENT PRIMARY KEY,
-- 	descricao VARCHAR(100) NOT NULL) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_CROATIAN_CI AUTO_INCREMENT=1;

-- CREATE TABLE permissoes (
--     codigo BIGINT AUTO_INCREMENT PRIMARY KEY,
--     descricao VARCHAR(100) NOT NULL
-- )  ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE = UTF8_CROATIAN_CI AUTO_INCREMENT=1;

-- CREATE TABLE usuario (
--     codigo BIGINT AUTO_INCREMENT PRIMARY KEY,
--     nome VARCHAR(100) NOT NULL,
--     email VARCHAR(100) NOT NULL,
--     senha VARCHAR(32) NOT NULL,
--     permissoes_id BIGINT(20),
--     CONSTRAINT permissoes_FK FOREIGN KEY (permissoes_id)
--         REFERENCES algamoneyapi.permissoes(codigo)
-- )  ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE = UTF8_CROATIAN_CI AUTO_INCREMENT=1;

-- CREATE TABLE item_permissoes( codigo BIGINT AUTO_INCREMENT PRIMARY KEY,
-- descricao VARCHAR(100) NOT NULL,
-- permissoes_id BIGINT NOT NULL,
-- permissao_id BIGINT NOT NULL,
-- FOREIGN KEY (permissoes_id) REFERENCES algamoneyapi.permissoes(codigo),
-- FOREIGN KEY (permissao_id) REFERENCES algamoneyapi.permissao(codigo) ) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE = UTF8_CROATIAN_CI AUTO_INCREMENT = 1;
